name: Build APK
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.0'
      
      - name: Unzip and Build
        run: |
          unzip AbuLaithERP.zip
          cd AbuLaithERP
          flutter create . --project-name abu_laith_erp --org com.abulaith .
          flutter pub get
          flutter build apk --release
      
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: AbuLaithERP/build/app/outputs/flutter-apk/app-release.apk
